name: CI

on:

   workflows_dispatch:
jobs:
  push_first_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "Checking out code..."
      - name: Run Tests
        run: echo "Running tests..."
